Add tests code
VedantParanjape/simpPRU pull request #12
Opened 2021-07-02 05:57 UTC by archisman-dey

This merge request adds the following features:
1. -c flag to stop after generating C code
2. -t flag to use stub functions
3. print() and println() while using -t

2021-07-12 19:52 UTC, VedantParanjape requested changes

2021-07-12 19:52 UTC, VedantParanjape commented on include/code_printer.h
> -#define _DT_BOOL_ "bool"
Don't remove this, let it be as it is.

2021-07-12 19:52 UTC, VedantParanjape commented on src/ast.c
> +
Remove the extra blank line

2021-07-12 19:52 UTC, VedantParanjape commented on src/ast.c
> +
Remove the extra blank line

2021-07-12 19:52 UTC, VedantParanjape commented on src/lexer.l
> +string               (\"(\\.|[^"\\])*\")
Please verify this on regex101.com, possibly share a prefilled link

2021-07-13 05:05 UTC, archisman-dey commented on src/lexer.l
> +string               (\"(\\.|[^"\\])*\")
What this does is: start with a ", then match zero or more of (either (a backslash followed by a character) or (any character except " or backslash)), then end with a "
Added some unit tests here: https://regex101.com/r/6PgGC8/2

2021-07-13 12:23 UTC, VedantParanjape commented on src/lexer.l
> +string               (\"(\\.|[^"\\])*\")
Cool, nice !

2021-07-13 12:24 UTC, merged