Add new for loop
VedantParanjape/simpPRU pull request #17
Opened 2021-07-28 09:37 UTC by archisman-dey

This PR adds the new for loop with increment expression, along with tests and documentation for the same.

2021-07-28 16:36 UTC, VedantParanjape requested changes

2021-07-28 16:36 UTC, VedantParanjape commented on src/code_printer.c
> +        fprintf(handle, "; %s < ", node->init->symbol_entry->identifier);
Remove the extra space in "; %s < "

2021-07-28 16:36 UTC, VedantParanjape commented on src/parser.y
> +                    KW_IN arithmetic_expression COLON arithmetic_expression loop_statement_for_increment compound_statement {
This implementation is correct, but can you rework it to match the complete project ? 

KW_IN arithmetic_expression COLON arithmetic_expression COLON arithmetic_expression 
| KW_IN arithmetic_expression COLON arithmetic_expression

so, instead of a new predicate, just go for a minimal way to do it.

2021-07-28 16:36 UTC, VedantParanjape commented on src/parser.y
> +%type <expression> arithmetic_expression boolean_expression relational_expression logical_expression return_statement function_call_datatypes loop_statement_for_increment
so this change will not be needed.

2021-07-28 19:47 UTC, archisman-dey commented on src/parser.y
> +                    KW_IN arithmetic_expression COLON arithmetic_expression loop_statement_for_increment compound_statement {
If I write it this way, I have to write
loop_statement_for: KW_FOR COLON IDENTIFIER {
                      $3->data_type = DT_INTEGER;}                    
                    KW_IN arithmetic_expression COLON arithmetic_expression compound_statement {
                      ...
                  }
                  | KW_FOR COLON IDENTIFIER {
                      $3->data_type = DT_INTEGER;}                    
                    KW_IN arithmetic_expression COLON arithmetic_expression COLON arithmetic_expression compound_statement {
                      ...
                  }
                  ;
The first part of both the rules are same, so bison shows a reduce/reduce conflict. The code and tests work, but it would be nice to compile without showing warnings.

2021-07-29 16:23 UTC, VedantParanjape commented on src/parser.y
> +                    KW_IN arithmetic_expression COLON arithmetic_expression loop_statement_for_increment compound_statement {
Right, I think there might be a way to fix those reduce/reduce conflict without going the way you went.

2021-07-29 16:36 UTC, VedantParanjape commented on src/parser.y
> +                    KW_IN arithmetic_expression COLON arithmetic_expression loop_statement_for_increment compound_statement {
I think it will be much neat if you do something like this"
```
KW_FOR COLON IDENTIFIER {
                      $3->data_type = DT_INTEGER;}                    
                    KW_IN range_expression compound_statement

range_expression : NUMBER 
        | NUMBER COMMA NUMBER
        | NUMBER COMMA NUMBER COMMA NUMBER
```

This is pretty much like what you did, but it makes it much better and configurable, i.e., you can now add quirks like range() in python can give.

Reference: https://github.com/jatin69/python-parser/blob/2bb50032bf399f78564c6c1c3d64af9a644630ea/python-loop-parser/loop-parser.y#L36

2021-07-29 21:48 UTC, archisman-dey commented on src/parser.y
> +                    KW_IN arithmetic_expression COLON arithmetic_expression loop_statement_for_increment compound_statement {
Changed it to be
```
loop_statement_for: KW_FOR COLON IDENTIFIER {
                      $3->data_type = DT_INTEGER;}                    
                    KW_IN range_expression compound_statement {
                      $3->value = $6->start->value;
                      $$ = create_loop_for_node(create_variable_node(AST_DT_INT, $3), $6, $7);
                  }
                  ;

range_expression: arithmetic_expression {
                        $$ = create_range_expression_node(NULL, $1, NULL);
                    }
                    | arithmetic_expression COLON arithmetic_expression {
                        $$ = create_range_expression_node($1, $3, NULL);
                    }
                    | arithmetic_expression COLON arithmetic_expression COLON arithmetic_expression {
                        $$ = create_range_expression_node($1, $3, $5);
                    }
                    ;
```
syntax for speicifying only stop condition looks odd though, so not sure whether to keep it or change something or not.

2021-07-30 18:53 UTC, VedantParanjape commented on src/parser.y
> +                    KW_IN arithmetic_expression COLON arithmetic_expression loop_statement_for_increment compound_statement {
Yeah, I agree the syntax for stop condition will be wierd looking, maybe do something like 
`COLON arithmetic_expression`

2021-07-31 07:43 UTC, archisman-dey commented on src/parser.y
> +                    KW_IN arithmetic_expression COLON arithmetic_expression loop_statement_for_increment compound_statement {
made this change

2021-08-01 17:53 UTC, merged